'use strict';

// 標準モジュールのロード
var fs = require('fs');


function kana2voca(string) {
  var str = string;

  // 3 characters
  str = str.replace(/う゛ぁ/g, ' b a');
  str = str.replace(/う゛ぃ/g, ' b i');
  str = str.replace(/う゛ぇ/g, ' b e');
  str = str.replace(/う゛ぉ/g, ' b o');
  str = str.replace(/う゛ゅ/g, ' by u');

  // 2 characters
  str = str.replace(/ぅ゛/g, ' b u');

  str = str.replace(/あぁ/g, ' a a');
  str = str.replace(/いぃ/g, ' i i');
  str = str.replace(/いぇ/g, ' i e');
  str = str.replace(/いゃ/g, ' y a');
  str = str.replace(/うぅ/g, ' u:');
  str = str.replace(/えぇ/g, ' e e');
  str = str.replace(/おぉ/g, ' o:');
  str = str.replace(/かぁ/g, ' k a:');
  str = str.replace(/きぃ/g, ' k i:');
  str = str.replace(/くぅ/g, ' k u:');
  str = str.replace(/くゃ/g, ' ky a');
  str = str.replace(/くゅ/g, ' ky u');
  str = str.replace(/くょ/g, ' ky o');
  str = str.replace(/けぇ/g, ' k e:');
  str = str.replace(/こぉ/g, ' k o:');
  str = str.replace(/がぁ/g, ' g a:');
  str = str.replace(/ぎぃ/g, ' g i:');
  str = str.replace(/ぐぅ/g, ' g u:');
  str = str.replace(/ぐゃ/g, ' gy a');
  str = str.replace(/ぐゅ/g, ' gy u');
  str = str.replace(/ぐょ/g, ' gy o');
  str = str.replace(/げぇ/g, ' g e:');
  str = str.replace(/ごぉ/g, ' g o:');
  str = str.replace(/さぁ/g, ' s a:');
  str = str.replace(/しぃ/g, ' sh i:');
  str = str.replace(/すぅ/g, ' s u:');
  str = str.replace(/すゃ/g, ' sh a');
  str = str.replace(/すゅ/g, ' sh u');
  str = str.replace(/すょ/g, ' sh o');
  str = str.replace(/せぇ/g, ' s e:');
  str = str.replace(/そぉ/g, ' s o:');
  str = str.replace(/ざぁ/g, ' z a:');
  str = str.replace(/じぃ/g, ' j i:');
  str = str.replace(/ずぅ/g, ' z u:');
  str = str.replace(/ずゃ/g, ' zy a');
  str = str.replace(/ずゅ/g, ' zy u');
  str = str.replace(/ずょ/g, ' zy o');
  str = str.replace(/ぜぇ/g, ' z e:');
  str = str.replace(/ぞぉ/g, ' z o:');
  str = str.replace(/たぁ/g, ' t a:');
  str = str.replace(/ちぃ/g, ' ch i:');
  str = str.replace(/つぁ/g, ' ts a');
  str = str.replace(/つぃ/g, ' ts i');
  str = str.replace(/つぅ/g, ' ts u:');
  str = str.replace(/つゃ/g, ' ch a');
  str = str.replace(/つゅ/g, ' ch u');
  str = str.replace(/つょ/g, ' ch o');
  str = str.replace(/つぇ/g, ' ts e');
  str = str.replace(/つぉ/g, ' ts o');
  str = str.replace(/てぇ/g, ' t e:');
  str = str.replace(/とぉ/g, ' t o:');
  str = str.replace(/だぁ/g, ' d a:');
  str = str.replace(/ぢぃ/g, ' j i:');
  str = str.replace(/づぅ/g, ' d u:');
  str = str.replace(/づゃ/g, ' zy a');
  str = str.replace(/づゅ/g, ' zy u');
  str = str.replace(/づょ/g, ' zy o');
  str = str.replace(/でぇ/g, ' d e:');
  str = str.replace(/どぉ/g, ' d o:');
  str = str.replace(/なぁ/g, ' n a:');
  str = str.replace(/にぃ/g, ' n i:');
  str = str.replace(/ぬぅ/g, ' n u:');
  str = str.replace(/ぬゃ/g, ' ny a');
  str = str.replace(/ぬゅ/g, ' ny u');
  str = str.replace(/ぬょ/g, ' ny o');
  str = str.replace(/ねぇ/g, ' n e:');
  str = str.replace(/のぉ/g, ' n o:');
  str = str.replace(/はぁ/g, ' h a:');
  str = str.replace(/ひぃ/g, ' h i:');
  str = str.replace(/ふぅ/g, ' f u:');
  str = str.replace(/ふゃ/g, ' hy a');
  str = str.replace(/ふゅ/g, ' hy u');
  str = str.replace(/ふょ/g, ' hy o');
  str = str.replace(/へぇ/g, ' h e:');
  str = str.replace(/ほぉ/g, ' h o:');
  str = str.replace(/ばぁ/g, ' b a:');
  str = str.replace(/びぃ/g, ' b i:');
  str = str.replace(/ぶぅ/g, ' b u:');
  str = str.replace(/ふゃ/g, ' hy a');
  str = str.replace(/ぶゅ/g, ' by u');
  str = str.replace(/ふょ/g, ' hy o');
  str = str.replace(/べぇ/g, ' b e:');
  str = str.replace(/ぼぉ/g, ' b o:');
  str = str.replace(/ぱぁ/g, ' p a:');
  str = str.replace(/ぴぃ/g, ' p i:');
  str = str.replace(/ぷぅ/g, ' p u:');
  str = str.replace(/ぷゃ/g, ' py a');
  str = str.replace(/ぷゅ/g, ' py u');
  str = str.replace(/ぷょ/g, ' py o');
  str = str.replace(/ぺぇ/g, ' p e:');
  str = str.replace(/ぽぉ/g, ' p o:');
  str = str.replace(/まぁ/g, ' m a:');
  str = str.replace(/みぃ/g, ' m i:');
  str = str.replace(/むぅ/g, ' m u:');
  str = str.replace(/むゃ/g, ' my a');
  str = str.replace(/むゅ/g, ' my u');
  str = str.replace(/むょ/g, ' my o');
  str = str.replace(/めぇ/g, ' m e:');
  str = str.replace(/もぉ/g, ' m o:');
  str = str.replace(/やぁ/g, ' y a:');
  str = str.replace(/ゆぅ/g, ' y u:');
  str = str.replace(/ゆゃ/g, ' y a:');
  str = str.replace(/ゆゅ/g, ' y u:');
  str = str.replace(/ゆょ/g, ' y o:');
  str = str.replace(/よぉ/g, ' y o:');
  str = str.replace(/らぁ/g, ' r a:');
  str = str.replace(/りぃ/g, ' r i:');
  str = str.replace(/るぅ/g, ' r u:');
  str = str.replace(/るゃ/g, ' ry a');
  str = str.replace(/るゅ/g, ' ry u');
  str = str.replace(/るょ/g, ' ry o');
  str = str.replace(/れぇ/g, ' r e:');
  str = str.replace(/ろぉ/g, ' r o:');
  str = str.replace(/わぁ/g, ' w a:');
  str = str.replace(/をぉ/g, ' o:');

  str = str.replace(/う゛/g, ' b u');
  str = str.replace(/でぃ/g, ' d i');
  str = str.replace(/でぇ/g, ' d e:');
  str = str.replace(/でゃ/g, ' dy a');
  str = str.replace(/でゅ/g, ' dy u');
  str = str.replace(/でょ/g, ' dy o');
  str = str.replace(/てぃ/g, ' t i');
  str = str.replace(/てぇ/g, ' t e:');
  str = str.replace(/てゃ/g, ' ty a');
  str = str.replace(/てゅ/g, ' ty u');
  str = str.replace(/てょ/g, ' ty o');
  str = str.replace(/すぃ/g, ' s i');
  str = str.replace(/ずぁ/g, ' z u a');
  str = str.replace(/ずぃ/g, ' z i');
  str = str.replace(/ずぅ/g, ' z u');
  str = str.replace(/ずゃ/g, ' zy a');
  str = str.replace(/ずゅ/g, ' zy u');
  str = str.replace(/ずょ/g, ' zy o');
  str = str.replace(/ずぇ/g, ' z e');
  str = str.replace(/ずぉ/g, ' z o');
  str = str.replace(/きゃ/g, ' ky a');
  str = str.replace(/きゅ/g, ' ky u');
  str = str.replace(/きょ/g, ' ky o');
  str = str.replace(/しゃ/g, ' sh a');
  str = str.replace(/しゅ/g, ' sh u');
  str = str.replace(/しぇ/g, ' sh e');
  str = str.replace(/しょ/g, ' sh o');
  str = str.replace(/ちゃ/g, ' ch a');
  str = str.replace(/ちゅ/g, ' ch u');
  str = str.replace(/ちぇ/g, ' ch e');
  str = str.replace(/ちょ/g, ' ch o');
  str = str.replace(/とぅ/g, ' t u');
  str = str.replace(/とゃ/g, ' ty a');
  str = str.replace(/とゅ/g, ' ty u');
  str = str.replace(/とょ/g, ' ty o');
  str = str.replace(/どぁ/g, ' d o a');
  str = str.replace(/どぅ/g, ' d u');
  str = str.replace(/どゃ/g, ' dy a');
  str = str.replace(/どゅ/g, ' dy u');
  str = str.replace(/どょ/g, ' dy o');
  str = str.replace(/どぉ/g, ' d o:');
  str = str.replace(/にゃ/g, ' ny a');
  str = str.replace(/にゅ/g, ' ny u');
  str = str.replace(/にょ/g, ' ny o');
  str = str.replace(/ひゃ/g, ' hy a');
  str = str.replace(/ひゅ/g, ' hy u');
  str = str.replace(/ひょ/g, ' hy o');
  str = str.replace(/みゃ/g, ' my a');
  str = str.replace(/みゅ/g, ' my u');
  str = str.replace(/みょ/g, ' my o');
  str = str.replace(/りゃ/g, ' ry a');
  str = str.replace(/りゅ/g, ' ry u');
  str = str.replace(/りょ/g, ' ry o');
  str = str.replace(/ぎゃ/g, ' gy a');
  str = str.replace(/ぎゅ/g, ' gy u');
  str = str.replace(/ぎょ/g, ' gy o');
  str = str.replace(/ぢぇ/g, ' j e');
  str = str.replace(/ぢゃ/g, ' j a');
  str = str.replace(/ぢゅ/g, ' j u');
  str = str.replace(/ぢょ/g, ' j o');
  str = str.replace(/じぇ/g, ' j e');
  str = str.replace(/じゃ/g, ' j a');
  str = str.replace(/じゅ/g, ' j u');
  str = str.replace(/じょ/g, ' j o');
  str = str.replace(/びゃ/g, ' by a');
  str = str.replace(/びゅ/g, ' by u');
  str = str.replace(/びょ/g, ' by o');
  str = str.replace(/ぴゃ/g, ' py a');
  str = str.replace(/ぴゅ/g, ' py u');
  str = str.replace(/ぴょ/g, ' py o');
  str = str.replace(/うぁ/g, ' u a');
  str = str.replace(/うぃ/g, ' w i');
  str = str.replace(/うぇ/g, ' w e');
  str = str.replace(/うぉ/g, ' w o');
  str = str.replace(/ふぁ/g, ' f a');
  str = str.replace(/ふぃ/g, ' f i');
  str = str.replace(/ふぅ/g, ' f u');
  str = str.replace(/ふゃ/g, ' hy a');
  str = str.replace(/ふゅ/g, ' hy u');
  str = str.replace(/ふょ/g, ' hy o');
  str = str.replace(/ふぇ/g, ' f e');
  str = str.replace(/ふぉ/g, ' f o');

  // 1 characters
  str = str.replace(/あ/g, ' a');
  str = str.replace(/い/g, ' i');
  str = str.replace(/う/g, ' u');
  str = str.replace(/え/g, ' e');
  str = str.replace(/お/g, ' o');
  str = str.replace(/か/g, ' k a');
  str = str.replace(/き/g, ' k i');
  str = str.replace(/く/g, ' k u');
  str = str.replace(/け/g, ' k e');
  str = str.replace(/こ/g, ' k o');
  str = str.replace(/さ/g, ' s a');
  str = str.replace(/し/g, ' sh i');
  str = str.replace(/す/g, ' s u');
  str = str.replace(/せ/g, ' s e');
  str = str.replace(/そ/g, ' s o');
  str = str.replace(/た/g, ' t a');
  str = str.replace(/ち/g, ' ch i');
  str = str.replace(/つ/g, ' ts u');
  str = str.replace(/て/g, ' t e');
  str = str.replace(/と/g, ' t o');
  str = str.replace(/な/g, ' n a');
  str = str.replace(/に/g, ' n i');
  str = str.replace(/ぬ/g, ' n u');
  str = str.replace(/ね/g, ' n e');
  str = str.replace(/の/g, ' n o');
  str = str.replace(/は/g, ' h a');
  str = str.replace(/ひ/g, ' h i');
  str = str.replace(/ふ/g, ' f u');
  str = str.replace(/へ/g, ' h e');
  str = str.replace(/ほ/g, ' h o');
  str = str.replace(/ま/g, ' m a');
  str = str.replace(/み/g, ' m i');
  str = str.replace(/む/g, ' m u');
  str = str.replace(/め/g, ' m e');
  str = str.replace(/も/g, ' m o');
  str = str.replace(/ら/g, ' r a');
  str = str.replace(/り/g, ' r i');
  str = str.replace(/る/g, ' r u');
  str = str.replace(/れ/g, ' r e');
  str = str.replace(/ろ/g, ' r o');
  str = str.replace(/が/g, ' g a');
  str = str.replace(/ぎ/g, ' g i');
  str = str.replace(/ぐ/g, ' g u');
  str = str.replace(/げ/g, ' g e');
  str = str.replace(/ご/g, ' g o');
  str = str.replace(/ざ/g, ' z a');
  str = str.replace(/じ/g, ' j i');
  str = str.replace(/ず/g, ' z u');
  str = str.replace(/ぜ/g, ' z e');
  str = str.replace(/ぞ/g, ' z o');
  str = str.replace(/だ/g, ' d a');
  str = str.replace(/ぢ/g, ' j i');
  str = str.replace(/づ/g, ' z u');
  str = str.replace(/で/g, ' d e');
  str = str.replace(/ど/g, ' d o');
  str = str.replace(/ば/g, ' b a');
  str = str.replace(/び/g, ' b i');
  str = str.replace(/ぶ/g, ' b u');
  str = str.replace(/べ/g, ' b e');
  str = str.replace(/ぼ/g, ' b o');
  str = str.replace(/ぱ/g, ' p a');
  str = str.replace(/ぴ/g, ' p i');
  str = str.replace(/ぷ/g, ' p u');
  str = str.replace(/ぺ/g, ' p e');
  str = str.replace(/ぽ/g, ' p o');
  str = str.replace(/や/g, ' y a');
  str = str.replace(/ゆ/g, ' y u');
  str = str.replace(/よ/g, ' y o');
  str = str.replace(/わ/g, ' w a');
  str = str.replace(/ゐ/g, ' i');
  str = str.replace(/ゑ/g, ' e');
  str = str.replace(/ん/g, ' N');
  str = str.replace(/っ/g, ' q');
  str = str.replace(/ー/g, ':');

  str = str.replace(/ぁ/g, ' a');
  str = str.replace(/ぃ/g, ' i');
  str = str.replace(/ぅ/g, ' u');
  str = str.replace(/ぇ/g, ' e');
  str = str.replace(/ぉ/g, ' o');
  str = str.replace(/ゎ/g, ' w a');
  str = str.replace(/ぉ/g, ' o');

  str = str.replace(/を/g, ' o');

  // other
  str = str.replace(/^\s+/, '');
  str = str.replace(/:+/g, ':');

  return str;
}

var JuliusDict = function(dictPath) {
  this.dictPath = dictPath;
  this.words = [];
};

JuliusDict.prototype.add = function(field1, field2) {
  this.words.push({field1: field1, field2: field2});
};

JuliusDict.prototype.make = function() {
  var data = '';

  for (var i = 0; this.words.length > i; i++) {
    data += this.words[i].field1 + '\t' + kana2voca(this.words[i].field2) + '\n';
  }

  fs.writeFileSync(this.dictPath, data);
};

module.exports = JuliusDict;

